/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutVolumesRouteImport } from './routes/_layout/volumes'
import { Route as LayoutSwapsRouteImport } from './routes/_layout/swaps'
import { Route as LayoutAssetsRouteImport } from './routes/_layout/assets'
import { Route as ApiAnalyticsEventsRouteImport } from './routes/api/analytics/events'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutVolumesRoute = LayoutVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSwapsRoute = LayoutSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssetsRoute = LayoutAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAnalyticsEventsRoute = ApiAnalyticsEventsRouteImport.update({
  id: '/api/analytics/events',
  path: '/api/analytics/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof LayoutAssetsRoute
  '/swaps': typeof LayoutSwapsRoute
  '/volumes': typeof LayoutVolumesRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof LayoutAssetsRoute
  '/swaps': typeof LayoutSwapsRoute
  '/volumes': typeof LayoutVolumesRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/assets': typeof LayoutAssetsRoute
  '/_layout/swaps': typeof LayoutSwapsRoute
  '/_layout/volumes': typeof LayoutVolumesRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assets' | '/swaps' | '/volumes' | '/api/analytics/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets' | '/swaps' | '/volumes' | '/api/analytics/events'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/assets'
    | '/_layout/swaps'
    | '/_layout/volumes'
    | '/api/analytics/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiAnalyticsEventsRoute: typeof ApiAnalyticsEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/volumes': {
      id: '/_layout/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof LayoutVolumesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/swaps': {
      id: '/_layout/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof LayoutSwapsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets': {
      id: '/_layout/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof LayoutAssetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/analytics/events': {
      id: '/api/analytics/events'
      path: '/api/analytics/events'
      fullPath: '/api/analytics/events'
      preLoaderRoute: typeof ApiAnalyticsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutAssetsRoute: typeof LayoutAssetsRoute
  LayoutSwapsRoute: typeof LayoutSwapsRoute
  LayoutVolumesRoute: typeof LayoutVolumesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAssetsRoute: LayoutAssetsRoute,
  LayoutSwapsRoute: LayoutSwapsRoute,
  LayoutVolumesRoute: LayoutVolumesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ApiAnalyticsEventsRoute: ApiAnalyticsEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
