import { ProviderInfoType } from "../contract";

export const PROVIDERS_LIST: ProviderInfoType[] = [
  {
    id: "across",
    label: "Across",
    category: "Intent-based Bridge",
    logoUrl: "https://3563890891-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fo33kX1T6RRp4inOcEH1d%2Fuploads%2FvmOkOcLgbiXv7hVNSlNT%2FAcross%20Logomark%20Aqua%20Circle.svg?alt=media&token=b63972b2-174f-4ee8-9a58-08fb8792cd17",
    supportedData: ["volumes", "assets"],
  },
  {
    id: "axelar",
    label: "Axelar",
    category: "GMP",
    logoUrl: "/images/provider-icons/axelar.png",
    supportedData: ["volumes"],
  },
  {
    id: "cashmere",
    label: "Cashmere",
    category: "Pool-based Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "ccip",
    label: "CCIP (Chainlink)",
    category: "GMP",
    supportedData: ["volumes"],
  },
  {
    id: "celer",
    label: "Celer cBridge",
    category: "Pool-based Bridge",
    logoUrl: "/images/provider-icons/cbridge.png",
    supportedData: ["volumes"],
  },
  {
    id: "chainflip",
    label: "Chainflip",
    category: "Intent-based Bridge",
    supportedData: [],
  },
  {
    id: "circle_cctp",
    label: "Circle CCTP",
    category: "Other Bridge",
    logoUrl: "/images/provider-icons/cctp.png",
    supportedData: ["volumes"],
  },
  {
    id: "debridge",
    label: "deBridge (DLN)",
    category: "Intent-based Bridge",
    logoUrl: "/images/provider-icons/debridge.png",
    supportedData: [],
  },
  {
    id: "everclear",
    label: "Everclear",
    category: "Clearing Protocol",
    supportedData: ["volumes"],
  },
  {
    id: "gaszip",
    label: "GasZip",
    category: "Other Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "hyperlane",
    label: "Hyperlane",
    category: "GMP",
    supportedData: ["volumes"],
  },
  {
    id: "layerzero",
    label: "LayerZero",
    category: "GMP",
    logoUrl: "/images/provider-icons/layerzero.png",
    supportedData: ["volumes"],
  },
  {
    id: "mayan",
    label: "Mayan",
    category: "Intent-based Bridge",
    supportedData: [],
  },
  {
    id: "meson",
    label: "Meson",
    category: "Pool-based Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "near_intents",
    label: "NEAR Intents",
    category: "Intent-based Bridge",
    logoUrl: "/images/provider-icons/near_intents.png",
    supportedData: ["volumes", "assets"],
  },
  {
    id: "oneinch",
    label: "1inch",
    category: "Bridge Aggregator",
    supportedData: ["volumes"],
  },
  {
    id: "orbiter",
    label: "Orbiter Finance",
    category: "Pool-based Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "relay",
    label: "Relay",
    category: "Intent-based Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "squid_axelar",
    label: "Squid (Axelar)",
    category: "Bridge Aggregator",
    supportedData: ["volumes"],
  },
  {
    id: "stargate",
    label: "Stargate",
    category: "Pool-based Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "synapse",
    label: "Synapse",
    category: "Pool-based Bridge",
    supportedData: ["volumes"],
  },
  {
    id: "wormhole",
    label: "Wormhole",
    category: "GMP",
    logoUrl: "/images/provider-icons/wormhole.png",
    supportedData: ["volumes"],
  },
  {
    id: "socket_bungee",
    label: "Socket (Bungee)",
    category: "Bridge Aggregator",
    supportedData: ["volumes"],
  },
  {
    id: "lifi",
    label: "LiFi",
    category: "Bridge Aggregator",
    logoUrl: "/images/provider-icons/lifi.png",
    supportedData: ["volumes"],
  },
  {
    id: "okx",
    label: "OKX Bridge",
    category: "Bridge Aggregator",
    supportedData: ["volumes"],
  },
  {
    id: "rango",
    label: "Rango Exchange",
    category: "Bridge Aggregator",
    supportedData: ["volumes"],
  },
  {
    id: "thorswap",
    label: "THORSwap",
    category: "Bridge Aggregator",
    supportedData: [],
  },
];